from . import res_connector
from . import license_attachments_spt
from . import license_spt
from . import license_types_management_spt
from . import locations_management_spt
from . import manufacturers_spt
from . import pack_size_type_spt
from . import pharma_dosage_forms
from . import product_requirement_conditions_spt
from . import product_category
from . import product_packaging_layer_spt
from . import product_identifier_spt
from . import product_description_spt
from . import product_composition_spt
from . import product_packaging_spt
from . import product_requirement_spt
from . import product
from . import product_spt
from . import purchase_order
from . import read_points_spt
from . import res_company
from . import res_config_settings
from . import res_country
from . import res_country_state
from . import res_partner
from . import sale_order
from . import shelf_spt
from . import stock_picking
from . import stock_production_lot
from . import storage_areas_spt
from . import thrid_party_logistic_provide_spt
from . import tracktrace_error_log_spt
from . import trading_partner_address_spt
from . import trading_partner_users_spt
from . import containers_spt
from . import location
