{
    'name': "To Do List",
    'summary': "Create Todo List Using Activities",
    'description': "Scheduling Activities For each model  and General Activities.",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': "https://www.cybrosys.com",
    'live_test_url': 'https://youtu.be/LGiDWPFdkbks',
    'category': 'Tools',
    'version': '14.0.2.0',
    'depends': ['base', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/recurring.xml',
        'data/general.xml',
        'views/mail_activity_view.xml',
        'views/templates.xml',
    ],
    "qweb": ["static/src/components/chatter_topbar/chatter_topbar.xml"],
    'license': 'LGPL-3',
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
    'application': True,
}
