{
    'name': 'TrackTraceRx2 API Integration Powered by TrackTraceRx ERP',
    'version': '14.0.0.4',
    'summary': 'Provide integration between odoo and Track TraceRx2',
    'author': 'tracktracerx.com',
    'sequence': 1,
    'license': 'AGPL-3',
    'website': 'https://www.tracktracerx.com',
    'category': 'Services',
    'description': "",
    'depends': [
        'base',
        'contacts',
        'board', 
        'sale_management', 
        'purchase', 
        'stock',
        'product',
        'product_expiry',
        'multi_step_wizard',
        'ttr_stock_lot',
        'ttr_location_management',
        'ttr_product_extra',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'views/assets.xml',
        'views/res_connector_view.xml',
        'views/default_configuratioan.xml',
        'views/res_company_view.xml',
        'views/trading_partner_address_spt_view.xml',
        'views/trading_partner_users_spt_view.xml',
        'views/license_spt_view.xml',
        'views/license_attachments_spt_view.xml',
        'views/res_partner_view.xml',
        'views/tracktrace_error_log_spt.xml',
        'views/product_view.xml',
        'views/product_template_form_view.xml',
        'views/product_spt_view.xml',
        'views/product_requirement_spt_view.xml',
        'views/license_types_management_spt_view.xml',
        'views/product_identifier_spt_view.xml',
        'views/product_description_spt_view.xml',
        'views/queue_spt_view.xml',
        'views/pack_size_type_spt_view.xml',
        'views/product_category_view.xml',
        'views/ttr2_dashboard_spt_view.xml',
        'views/locations_management_spt_view.xml',
        'views/stock_production_lot_view.xml',
        'views/stock_picking_view.xml',
        'views/storage_areas_spt_view.xml',
        'views/shelf_spt_view.xml',
        'views/read_points_spt_view.xml',
        'views/thrid_party_logistic_provide_spt_view.xml',
        'views/manufacturers_spt_view.xml',
        'views/pharma_dosage_forms.xml',
        'views/purchase_order.xml',
        'views/picking_spt_view.xml',
        'views/sale_order.xml',
        'views/res_config_settings_views.xml',
        'views/containers_spt_view.xml',
        'views/menu_view.xml',
        # EPCIS Front-End Views - WIP
        # 'views/copy_epcis_aggregation_and_disaggregation_custom_2nd_party.xml',
        'wizard/sync_partner_view.xml',
        'wizard/sync_product_view.xml',
        'wizard/sync_manufacturer_view.xml',
        'wizard/sync_locations_view.xml',
        'wizard/sync_container_view.xml',
        'wizard/sync_sale_view.xml',
        'wizard/sync_purchase_view.xml',
        'wizard/sync_receipt_view.xml',
        'wizard/sync_delivery_view.xml',
        'data/schedular_action.xml',
        # 'data/connector_data.xml',
    ],
    'qweb': ['static/src/xml/dashboard.xml'],
    'application': True,
    'installable': True,
    'auto_install': False,
}
